<a href="https://colab.research.google.com/github/babaghaarmaan123/studypilot-ai/blob/main/Mushroom.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
sns.set_style('dark')
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split, cross_val_score, cross_validate

from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn import metrics
from sklearn.metrics import accuracy_score

In [13]:
mushroom = pd.read_csv('/mushrooms.csv')

In [14]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [15]:
mushroom

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,e,k,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,b,c,l
8120,e,x,s,n,f,n,a,c,b,y,...,s,o,o,p,n,o,p,b,v,l
8121,e,f,s,n,f,n,a,c,b,n,...,s,o,o,p,o,o,p,b,c,l
8122,p,k,y,n,f,y,f,c,n,b,...,k,w,w,p,w,o,e,w,v,l
8123,e,x,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,o,c,l

In [16]:
mushroom.isnull().sum()

class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

In [17]:
mushroom.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   class                     8124 non-null   object
 1   cap-shape                 8124 non-null   object
 2   cap-surface               8124 non-null   object
 3   cap-color                 8124 non-null   object
 4   bruises                   8124 non-null   object
 5   odor                      8124 non-null   object
 6   gill-attachment           8124 non-null   object
 7   gill-spacing              8124 non-null   object
 8   gill-size                 8124 non-null   object
 9   gill-color                8124 non-null   object
 10  stalk-shape               8124 non-null   object
 11  stalk-root                8124 non-null   object
 12  stalk-surface-above-ring  8124 non-null   object
 13  stalk-surface-below-ring  8124 non-null   object
 14  stalk-color-above-ring    8124 non-null   object
 15  stalk-color-below-ring    8124 non-null   object
 16  veil-type                 8124 non-null   object
 17  veil-color                8124 non-null   object
 18  ring-number               8124 non-null   object
 19  ring-type                 8124 non-null   object
 20  spore-print-color         8124 non-null   object
 21  population                8124 non-null   object
 22  habitat                   8124 non-null   object
dtypes: object(23)
memory usage: 1.4+ MB

classes: edible = e, poisonous = p

cap-shape: bell = b, conical = c, convex = x, flat = f, knobbed = k, sunken = s

cap-surface: fibrous = f, grooves = g, scaly = y, smooth = s

cap-color: brown = n, buff = b, cinnamon = c, gray = g, green = r, pink = p, purple = u, red = e, white = w, yellow = y

bruises: yes = t, no = f

odor: almond = a, anise = l, creosote = c, fishy = y, foul = f, musty = m, none = n, pungent = p, spicy = s

gill-attachment: attached = a, descending = d, free = f, notched = n

gill-spacing: close = c, crowded = w, distant = d

gill-size: broad = b, narrow = n

gill-color: black = k, brown = n, buff = b, chocolate = h, gray = g, green = r, orange = o, pink = p, purple = u, red = e, white = w ,yellow = y

stalk-shape: enlarging = e, tapering = t

stalk-root: bulbous = b, club = c, cup = u, equal = e, rhizomorphs = z, rooted = r, missing = ?

stalk-surface-above-ring: fibrous = f, scaly = y, silky = k, smooth = s

stalk-surface-below-ring: fibrous = f, scaly = y, silky = k, smooth = s

stalk-color-above-ring: brown = n, buff = b, cinnamon = c, gray = g, orange = o, pink = p, red = e, white = w, yellow = y

stalk-color-below-ring: brown = n, buff = b, cinnamon = c, gray = g, orange = o, pink = p, red = e, white = w, yellow = y

veil-type: partial = p, universal = u

veil-color: brown = n, orange = o, white = w, yellow = y

ring-number: none = n, one = o, two = t

ring-type: cobwebby = c, evanescent = e, flaring = f, large = l, none = n, pendant = p, sheathing = s, zone = z

spore-print-color: black = k, brown = n, buff = b, chocolate = h, green = r, orange = o,purple = u, white = w, yellow = y

population: abundant = a, clustered = c, numerous = n, scattered = s, several = v, solitary = y

habitat: grasses = g, leaves = l, meadows = m, paths = p, urban = u, waste = w, woods = d

In [18]:
mushroom['class'].value_counts().to_frame()

       count
class
e       4208
p       3916

e=51.8%
p=48.2%

In [19]:
mushroom.groupby(['cap-shape'])['class'].value_counts().to_frame()

                 count
cap-shape class
b         e        404
          p         48
c         p          4
f         e       1596
          p       1556
k         p        600
          e        228
s         e         32
x         e       1948
          p       1708

In [20]:
mushroom.groupby(['cap-surface'])['class'].value_counts().to_frame()

                   count
cap-surface class
f           e       1560
            p        760
g           p          4
s           p       1412
            e       1144
y           p       1740
            e       1504

In [21]:
mushroom.groupby(['cap-color'])['class'].value_counts().to_frame()

                 count
cap-color class
b         p        120
          e         48
c         e         32
          p         12
e         p        876
          e        624
g         e       1032
          p        808
n         e       1264
          p       1020
p         p         88
          e         56
r         e         16
u         e         16
w         e        720
          p        320
y         p        672
          e        400

In [22]:
mushroom.groupby(['bruises'])['class'].value_counts().to_frame()

               count
bruises class
f       p       3292
        e       1456
t       e       2752
        p        624

In [23]:
mushroom.groupby(['odor'])['class'].value_counts().to_frame()

            count
odor class
a    e        400
c    p        192
f    p       2160
l    e        400
m    p         36
n    e       3408
     p        120
p    p        256
s    p        576
y    p        576

In [24]:
mushroom.groupby(['gill-attachment'])['class'].value_counts().to_frame()

                       count
gill-attachment class
a               e        192
                p         18
f               e       4016
                p       3898

In [25]:
mushroom.groupby(['gill-spacing'])['class'].value_counts().to_frame()

                    count
gill-spacing class
c            p       3804
             e       3008
w            e       1200
             p        112

In [26]:
mushroom.groupby(['gill-size'])['class'].value_counts().to_frame()

                 count
gill-size class
b         e       3920
          p       1692
n         p       2224
          e        288

In [27]:
mushroom.groupby(['gill-color'])['class'].value_counts().to_frame()

                  count
gill-color class
b          p       1728
e          e         96
g          p        504
           e        248
h          p        528
           e        204
k          e        344
           p         64
n          e        936
           p        112
o          e         64
p          e        852
           p        640
r          p         24
u          e        444
           p         48
w          e        956
           p        246
y          e         64
           p         22

In [28]:
mushroom.groupby(['gill-attachment'])['class'].value_counts().to_frame()

                       count
gill-attachment class
a               e        192
                p         18
f               e       4016
                p       3898

In [29]:
mushroom.groupby(['stalk-shape'])['class'].value_counts().to_frame()

                   count
stalk-shape class
e           p       1900
            e       1616
t           e       2592
            p       2016

In [30]:
mushroom.groupby(['stalk-root'])['class'].value_counts().to_frame()

                  count
stalk-root class
?          p       1760
           e        720
b          e       1920
           p       1856
c          e        512
           p         44
e          e        864
           p        256
r          e        192

In [31]:
mushroom.groupby(['stalk-surface-above-ring'])['class'].value_counts().to_frame()

                                count
stalk-surface-above-ring class
f                        e        408
                         p        144
k                        p       2228
                         e        144
s                        e       3640
                         p       1536
y                        e         16
                         p          8

In [32]:
mushroom.groupby(['stalk-surface-below-ring'])['class'].value_counts().to_frame()

                                count
stalk-surface-below-ring class
f                        e        456
                         p        144
k                        p       2160
                         e        144
s                        e       3400
                         p       1536
y                        e        208
                         p         76

In [33]:
mushroom.groupby(['stalk-surface-above-ring'])['class'].value_counts().to_frame()

                                count
stalk-surface-above-ring class
f                        e        408
                         p        144
k                        p       2228
                         e        144
s                        e       3640
                         p       1536
y                        e         16
                         p          8

In [34]:
mushroom.groupby(['stalk-color-above-ring'])['class'].value_counts().to_frame()

                              count
stalk-color-above-ring class
b                      p        432
c                      p         36
e                      e         96
g                      e        576
n                      p        432
                       e         16
o                      e        192
p                      p       1296
                       e        576
w                      e       2752
                       p       1712
y                      p          8

In [35]:
mushroom.groupby(['stalk-color-below-ring'])['class'].value_counts().to_frame()

                              count
stalk-color-below-ring class
b                      p        432
c                      p         36
e                      e         96
g                      e        576
n                      p        448
                       e         64
o                      e        192
p                      p       1296
                       e        576
w                      e       2704
                       p       1680
y                      p         24

In [36]:
mushroom.groupby(['veil-type'])['class'].value_counts().to_frame()

                 count
veil-type class
p         e       4208
          p       3916

In [37]:
mushroom.groupby(['veil-color'])['class'].value_counts().to_frame()

                  count
veil-color class
n          e         96
o          e         96
w          e       4016
           p       3908
y          p          8

In [38]:
mushroom.groupby(['ring-number'])['class'].value_counts().to_frame()

                   count
ring-number class
n           p         36
o           p       3808
            e       3680
t           e        528
            p         72

In [39]:
mushroom.groupby(['ring-type'])['class'].value_counts().to_frame()

                 count
ring-type class
e         p       1768
          e       1008
f         e         48
l         p       1296
n         p         36
p         e       3152
          p        816

In [40]:
mushroom.groupby(['spore-print-color'])['class'].value_counts().to_frame()

                         count
spore-print-color class
b                 e         48
h                 p       1584
                  e         48
k                 e       1648
                  p        224
n                 e       1744
                  p        224
o                 e         48
r                 p         72
u                 e         48
w                 p       1812
                  e        576
y                 e         48

In [41]:
mushroom.groupby(['population'])['class'].value_counts().to_frame()

                  count
population class
a          e        384
c          e        288
           p         52
n          e        400
s          e        880
           p        368
v          p       2848
           e       1192
y          e       1064
           p        648

In [42]:
mushroom.groupby(['habitat'])['class'].value_counts().to_frame()

               count
habitat class
d       e       1880
        p       1268
g       e       1408
        p        740
l       p        592
        e        240
m       e        256
        p         36
p       p       1008
        e        136
u       p        272
        e         96
w       e        192

There are no grooves type cap-surface mushrooms at all.

Mushrooms with bruises are mainly edible and mushrooms with no bruises are mainly poisoneous

creosote,fishy,foul,musty and spicy odor mushrooms are poisoneous.

Maximum mushrooms are free gill-attached , close gill-spacing (max poisoneous) and narrow gill - size (max edible).

Buff and green gill colored mushrooms are edible.

bulbous stalk root mushrroms are maximum

silky stalk-surface-above-ring mushrooms are mainly poisoneous and smooth

stalk-surface-above-ring mushrooms are mainly edible

silky stalk-surface-below-ring mushrooms are mainly poisoneous and smooth

stalk-surface-below-ring mushrooms are mainly edible.

orange and red stalk color above ring mushrooms are poisoneous.

brown and orange veil color mushrooms are poisoneous.

Buff , green , yellow , brown , orange spore print color mushrooms are mainly poisoneous.

numerous and abandant mushrooms are mainly poisoneous.

In [43]:
mushroom.drop(columns=['veil-type'],axis=  1,inplace=True)

In [44]:
def Label_enc(column):
  LE=LabelEncoder()
  LE.fit(column)
  print(column.name,LE.classes_)
  return LE.transform(column)

In [45]:
for i in mushroom.columns:
  mushroom[str(i)] = Label_enc(mushroom[str(i)])

class ['e' 'p']
cap-shape ['b' 'c' 'f' 'k' 's' 'x']
cap-surface ['f' 'g' 's' 'y']
cap-color ['b' 'c' 'e' 'g' 'n' 'p' 'r' 'u' 'w' 'y']
bruises ['f' 't']
odor ['a' 'c' 'f' 'l' 'm' 'n' 'p' 's' 'y']
gill-attachment ['a' 'f']
gill-spacing ['c' 'w']
gill-size ['b' 'n']
gill-color ['b' 'e' 'g' 'h' 'k' 'n' 'o' 'p' 'r' 'u' 'w' 'y']
stalk-shape ['e' 't']
stalk-root ['?' 'b' 'c' 'e' 'r']
stalk-surface-above-ring ['f' 'k' 's' 'y']
stalk-surface-below-ring ['f' 'k' 's' 'y']
stalk-color-above-ring ['b' 'c' 'e' 'g' 'n' 'o' 'p' 'w' 'y']
stalk-color-below-ring ['b' 'c' 'e' 'g' 'n' 'o' 'p' 'w' 'y']
veil-color ['n' 'o' 'w' 'y']
ring-number ['n' 'o' 't']
ring-type ['e' 'f' 'l' 'n' 'p']
spore-print-color ['b' 'h' 'k' 'n' 'o' 'r' 'u' 'w' 'y']
population ['a' 'c' 'n' 's' 'v' 'y']
habitat ['d' 'g' 'l' 'm' 'p' 'u' 'w']

In [46]:
mushroom.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-above-ring,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,1,5,2,4,1,6,1,0,1,4,...,2,2,7,7,2,1,4,2,3,5
1,0,5,2,9,1,0,1,0,0,4,...,2,2,7,7,2,1,4,3,2,1
2,0,0,2,8,1,3,1,0,0,5,...,2,2,7,7,2,1,4,3,2,3
3,1,5,3,8,1,6,1,0,1,5,...,2,2,7,7,2,1,4,2,3,5
4,0,5,2,3,0,5,1,1,0,4,...,2,2,7,7,2,1,0,3,0,1

In [47]:
x = mushroom.drop(columns=['class'], axis=1)
y=mushroom['class']

In [48]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [49]:
model=RandomForestClassifier()
model.fit(x_train, y_train)
y_predict = model.predict(x_test)

In [50]:
print("The accuracy of the model is", accuracy_score(y_predict, y_test))

The accuracy of the model is 1.0

In [51]:
import joblib as jl

In [52]:
jl.dump(model,"mushrooms.pkl")

['mushrooms.pkl']

In [53]:
input123=jl.load("mushrooms.pkl")

In [54]:
mushroom.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-above-ring,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,1,5,2,4,1,6,1,0,1,4,...,2,2,7,7,2,1,4,2,3,5
1,0,5,2,9,1,0,1,0,0,4,...,2,2,7,7,2,1,4,3,2,1
2,0,0,2,8,1,3,1,0,0,5,...,2,2,7,7,2,1,4,3,2,3
3,1,5,3,8,1,6,1,0,1,5,...,2,2,7,7,2,1,4,2,3,5
4,0,5,2,3,0,5,1,1,0,4,...,2,2,7,7,2,1,0,3,0,1

In [55]:
mushroom["stalk-shape"].unique()

array([0, 1])

In [56]:
mushroom["stalk-root"].unique()

array([3, 2, 1, 4, 0])

In [57]:
mushroom.iloc[0]

class                       1
cap-shape                   5
cap-surface                 2
cap-color                   4
bruises                     1
odor                        6
gill-attachment             1
gill-spacing                0
gill-size                   1
gill-color                  4
stalk-shape                 0
stalk-root                  3
stalk-surface-above-ring    2
stalk-surface-below-ring    2
stalk-color-above-ring      7
stalk-color-below-ring      7
veil-color                  2
ring-number                 1
ring-type                   4
spore-print-color           2
population                  3
habitat                     5
Name: 0, dtype: int64

In [58]:
def get_integer_input(prompt):
    while True:
        user_input = input(prompt)
        try:
            return int(user_input)
        except ValueError:
            print("Invalid input. Please enter a valid integer.")

cap_shape = get_integer_input("Enter the value for cap-shape, any number from 0-5: ")
cap_surface= get_integer_input("Enter the value for cap-surface, any number from 0-5: ")
cap_color= get_integer_input("Enter the value for cap-color any number from 0-5: ")
bruises= get_integer_input("Enter the value for bruises, any number from 0-5: ")
odor= get_integer_input("Enter the value for odor, any number from 0-5: ")
gill_attachment=get_integer_input("Enter the value for gill-attachment, any number from 0-5: ")
gill_spacing=get_integer_input("Enter the value for gill-spacing, any number from 0-5: ")
gill_size=get_integer_input("Enter the value for gill-size, any number from 0-5: ")
gill_color=get_integer_input("Enter the value for gill-color, any number from 0-5: ")
stalk_shape=get_integer_input("Enter the value for stalk-shape, any number from 0-5: ")
stalk_root=get_integer_input("Enter the value for stalk-root, any number from 0-5: ")
stalk_surface_above_ring=get_integer_input("Enter the value for stalk-surface-above-ring, any number from 0-5: ")
stalk_surface_below_ring=get_integer_input("Enter the value for stalk-surface-below-ring:, any number from 0-5: ")
stalk_color_above_ring=get_integer_input("Enter the value for stalk-color-above-ring:, any number from 0-5: ")
stalk_color_below_ring=get_integer_input("Enter the value for stalk-color-below-ring:, any number from 0-5: ")
veil_color=get_integer_input("Enter the value for veil-color, any number from 0-5: ")
ring_number=get_integer_input("Enter the value for ring-number, any number from 0-5: ")
ring_type=get_integer_input("Enter the value for ring-type, any number from 0-5: ")
spore_print_color=get_integer_input("Enter the value for spore-print-color, any number from 0-5: ")
population=get_integer_input("Enter the value for population, any number from 0-5: ")
habitat=get_integer_input("Enter the value for habitat, any number from 0-5: ")


Edibility = input123.predict([[cap_shape,cap_surface,cap_color,bruises,odor,gill_attachment,gill_spacing,gill_size,gill_color,stalk_shape,stalk_root,stalk_surface_above_ring,stalk_surface_below_ring,stalk_color_above_ring,stalk_color_below_ring,veil_color,ring_number,ring_type,spore_print_color,population,habitat]])[0]

if Edibility==1:
  print("the mushroom is edibile")
else:
  print("the mushroom is inedibile")

Enter the value for cap-shape, any number from 0-5: 1
Enter the value for cap-surface, any number from 0-5: 2
Enter the value for cap-color any number from 0-5: 4
Enter the value for bruises, any number from 0-5: 1
Enter the value for odor, any number from 0-5: 2
Enter the value for gill-attachment, any number from 0-5: 3
Enter the value for gill-spacing, any number from 0-5: 1
Enter the value for gill-size, any number from 0-5: 1
Enter the value for gill-color, any number from 0-5: 2
Enter the value for stalk-shape, any number from 0-5: 3
Enter the value for stalk-root, any number from 0-5: 2
Enter the value for stalk-surface-above-ring, any number from 0-5: 2
Enter the value for stalk-surface-below-ring:, any number from 0-5: 2
Enter the value for stalk-color-above-ring:, any number from 0-5: 2
Enter the value for stalk-color-below-ring:, any number from 0-5: 2
Enter the value for veil-color, any number from 0-5: 2
Enter the value for ring-number, any number from 0-5: 2
Enter the value for ring-type, any number from 0-5: 2
Enter the value for spore-print-color, any number from 0-5: 2
Enter the value for population, any number from 0-5: 2
Enter the value for habitat, any number from 0-5: 3
the mushroom is inedibile